baseurl: /
repository: phpearth/php-lands
title: The PHP Lands Map
description: Explore the PHP language and ecosystem in a fun and interactive way using a pirate map.
exclude:
  - bin
  - node_modules
  - src
  - .editorconfig
  - CNAME
  - CONTRIBUTING.md
  - LICENSE
  - Makefile
  - package.json
  - README.md
  - webpack.config.js
  - yarn.lock
  - yarn-error.log
app:
  map_url: https://raw.githubusercontent.com/phpearth/assets/master/php-lands/v0.8
  asset_version: v5
